### PR TITLE
Add FAIRDOM acronym in full to About page

### PR DESCRIPTION
**Pull request by PhilReedData**
Added a sentence after the other text to clearly explain what the DOM letters stand for. I could not find a way to work it into the earlier sentences, they are so neatly crafted that I would be spoiling them, they would no longer flow well.

(If there are any other changes I would like you to review, I'll put them in a batch together next week. This one might require some more careful thought and consultation.)

### CODE REVIEW

**Comment by smza** [comment]
How about we write it like this:

The primary mission is to assist researchers, students, trainers, funders, and publishers in making their data, documents, operating procedures, and models Findable, Accessible, Interoperable, and Reusable (FAIR) through collaborative projects. This is indeed the basis of FAIRDOM acronym, which stands for Findable, Accessible, Interoperable, and Reusable Documents, Operations, and Models.

**Comment by stuzart** [comment]
The D stands for Data, not Documents.

A problem with explaining what they stand for is that it is now a little redundant as we cover other types as well, so it makes us sound more limited than we really are

**Comment by smza** [comment]
> The D stands for Data, not Documents.
> 
> A problem with explaining what they stand for is that it is now a little redundant as we cover other types as well, so it makes us sound more limited than we really are

@stuzart do you suggest we leave it unexplained?

**Comment by PhilReedData** [comment]
Stuart mentioned to me that the [FAIRDOMHub page](https://fair-dom.org/fairdom-in-use/fairdomhub) explains the acronym. It is not particularly obvious, though. Is that enough?

**Comment by smza** [comment]
> Stuart mentioned to me that the [FAIRDOMHub page](https://fair-dom.org/fairdom-in-use/fairdomhub) explains the acronym. It is not particularly obvious, though. Is that enough?

OK. Even on the this page it says D stands for Data and as @stuzart says it should be documents.  Lets leave it unexplained in the landing page then!

**Comment by PhilReedData** [comment]
Thanks Stuart and Munazah, I will withdraw the acronym change, closing the PR.

**Pull request closed without merging**
